SELECT 

/**
Modificaciones:

15-03-2019: se modificó (en solicitud 001262) el responsable de la tarea pendiente. Específicamente, se cambio:
TAREAS_PENDIENTES.NMUSER RESPONSABLE_TAREA
por
(select u.nmuser from aduser u where u.cduser = TAREAS_PENDIENTES.CDUSER ) RESPONSABLE_TAREA
22-04-2019: se incluyeron los 6 campos de análisis de causa:
TEMPANA.AC_Metodo,
TEMPANA.AC_Maquinaria,
TEMPANA.AC_Mano_Obra,
TEMPANA.AC_Medio_Ambiente,
TEMPANA.AC_Medicion,
TEMPANA.AC_Material,
29-05-2020. Se convirtió en varchar el campo descripción, ya que tras la migración el campo es tipo CLOB
01-06-2020. Inclusión de plazo de tarea y actualización de fracción de query que consulta las tareas pendientes.
12-08-2020: Conversion de BIGTEXT A TEXT Para campo direccion.
04-09-2020: Conversión de BIGTEST A TEXT para campos AREA_DEL_RESPONSABLE_TAREA y area_hall
23-09-2020: Ajuste de query teniendo en cuenta cambio en modelo de datos: la relación entre hallazgos y formulario 
no usa las tablas GNFORMREGGROUP y GNFORMREG, sino GNASSOCFORMREG
23-09-2020: Inclusión de fecha de plazo de la tarea pendiente
**/


ESTADO_TAREAS.PLAZO PLAZO_TAREA, 

CAST((select d.iddepartment || ' - ' || d.nmdepartment from aduserdeptpos udp join addepartment d on d.cddepartment = udp.cddepartment where 

udp.fgdefaultdeptpos = 1 and udp.cduser = TAREAS_PENDIENTES.cduser ) as VARCHAR(255)) AREA_DEL_RESPONSABLE_TAREA,
(select u.nmuser from aduser u where u.cduser = TAREAS_PENDIENTES.CDUSER ) RESPONSABLE_TAREA, TAREAS_PENDIENTES.DTDEADLINEFIELD AS FECHA_PLAZO_TAREA, TEMP2.* FROM (SELECT 

TEMPANA.cdprocess,
TEMPANA.id_hallazgo,        
TEMPANA.nombre_proceso,   
TEMPANA.titulo_hallazgo,
TEMPANA.cantidad,	  	  	

CASE WHEN TEMPANA.identificador is null THEN TEMPANA.id_hallazgo else TEMPANA.identificador END identificador,

NVL(TO_CHAR(tempana.fecha_deteccion,'YYYY-MM-DD HH24:MI:SS'),tempana.dtstart) fecha_deteccion,

TEMPANA.DTSTART AS FECHA_INICIO,
TEMPANA.DTFINISH AS FECHA_FIN,
TEMPANA.DAYS_FROM_START,
TEMPANA.DIAS_DESDE_INICIO,
TEMPANA.NUM_DIAS_DESDE_INICIO,

CAST(CASE WHEN TEMPANA.dir_regional = ' - ' THEN (SELECT NMATTRIBUTE FROM ADATTRIBVALUE ADATV,WFPROCATTRIB WFPROCA WHERE TEMPANA.IDOBJECT=WFPROCA.IDPROCESS AND WFPROCA.CDATTRIBUTE = ADATV.CDATTRIBUTE AND WFPROCA.CDVALUE=ADATV.CDVALUE AND WFPROCA.CDATTRIBUTE=292) else TEMPANA.dir_regional END AS VARCHAR(255)) dir_regional_division,

CAST(CASE WHEN TEMPANA.area_hall = ' - ' THEN (SELECT NMATTRIBUTE FROM ADATTRIBVALUE ADATV,WFPROCATTRIB WFPROCA WHERE TEMPANA.IDOBJECT=WFPROCA.IDPROCESS 

AND WFPROCA.CDATTRIBUTE = ADATV.CDATTRIBUTE AND WFPROCA.CDVALUE=ADATV.CDVALUE AND WFPROCA.CDATTRIBUTE=293) else TEMPANA.area_hall END AS VARCHAR(255)) area_hall,

CASE WHEN TEMPANA.nombre_quien_detec is null THEN tempana.NMUSERSTART else TEMPANA.nombre_quien_detec END nombre_quien_detec,

CASE WHEN TEMPANA.nombre_res_proc is null THEN 'Atributo no definido en hallazgo' else TEMPANA.nombre_res_proc END nombre_res_proc,

CASE WHEN TEMPANA.req_normativo is null THEN (SELECT NMATTRIBUTE FROM ADATTRIBVALUE ADATV,WFPROCATTRIB WFPROCA WHERE 

TEMPANA.IDOBJECT=WFPROCA.IDPROCESS
AND WFPROCA.CDATTRIBUTE = ADATV.CDATTRIBUTE AND WFPROCA.CDVALUE=ADATV.CDVALUE AND WFPROCA.CDATTRIBUTE=7) else TEMPANA.req_normativo END 

clau_normativa,

CASE WHEN TEMPANA.macroproceso is null THEN (SELECT NMATTRIBUTE FROM ADATTRIBVALUE ADATV,WFPROCATTRIB WFPROCA WHERE 

TEMPANA.IDOBJECT=WFPROCA.IDPROCESS
AND WFPROCA.CDATTRIBUTE = ADATV.CDATTRIBUTE AND WFPROCA.CDVALUE=ADATV.CDVALUE AND WFPROCA.CDATTRIBUTE=294) else TEMPANA.macroproceso END 

macroproceso,

CASE WHEN TEMPANA.proceso is null THEN (SELECT NMATTRIBUTE FROM ADATTRIBVALUE ADATV,WFPROCATTRIB WFPROCA WHERE TEMPANA.IDOBJECT=WFPROCA.IDPROCESS
AND WFPROCA.CDATTRIBUTE = ADATV.CDATTRIBUTE AND WFPROCA.CDVALUE=ADATV.CDVALUE AND WFPROCA.CDATTRIBUTE=295) else TEMPANA.proceso END proceso,

/**
CASE WHEN TEMPANA.subproceso is null THEN (SELECT NMATTRIBUTE FROM ADATTRIBVALUE ADATV,WFPROCATTRIB WFPROCA WHERE TEMPANA.IDOBJECT=WFPROCA.IDPROCESS
AND WFPROCA.CDATTRIBUTE = ADATV.CDATTRIBUTE AND WFPROCA.CDVALUE=ADATV.CDVALUE AND WFPROCA.CDATTRIBUTE=296) else TEMPANA.subproceso END subproceso,
**/

CASE WHEN dbms_lob.substr(TEMPANA.desc_hallazgo,4000,1) is null THEN dbms_lob.substr(TEMPANA.dsoccurrence,4000,1) else dbms_lob.substr(TEMPANA.desc_hallazgo,4000,1) END desc_hallazgo,

TEMPANA.estado_proceso,

TEMPANA.estado_hallazgo,

TEMPANA.situacion_hallazgo,

TEMPANA.tipo_hallazgo,


CASE WHEN TEMPANA.fuente_origen = 'Sin seleccionar' THEN (SELECT NMATTRIBUTE FROM ADATTRIBVALUE ADATV,WFPROCATTRIB WFPROCA WHERE 

TEMPANA.IDOBJECT=WFPROCA.IDPROCESS
AND WFPROCA.CDATTRIBUTE = ADATV.CDATTRIBUTE AND WFPROCA.CDVALUE=ADATV.CDVALUE AND WFPROCA.CDATTRIBUTE=266) else TEMPANA.fuente_origen END 

fuente_origen,

TEMPANA.cargo_resp_acc_1,
TEMPANA.resp_acc_1,
TEMPANA.plazo_acc_1,
TEMPANA.comp_acc_1,
TEMPANA.ejecucion_acc_1,

TEMPANA.cargo_resp_acc_2,
TEMPANA.resp_acc_2,
TEMPANA.plazo_acc_2,
TEMPANA.comp_acc_2,
TEMPANA.ejecucion_acc_2,

TEMPANA.cargo_resp_acc_3,
TEMPANA.resp_acc_3,
TEMPANA.plazo_acc_3,
TEMPANA.comp_acc_3,
TEMPANA.ejecucion_acc_3,

TEMPANA.cargo_resp_acc_4,
TEMPANA.resp_acc_4,
TEMPANA.plazo_acc_4,
TEMPANA.comp_acc_4,
TEMPANA.ejecucion_acc_4,

TEMPANA.cargo_resp_acc_5,
TEMPANA.resp_acc_5,
TEMPANA.plazo_acc_5,
TEMPANA.comp_acc_5,
TEMPANA.ejecucion_acc_5,

TEMPANA.AC_Metodo,
TEMPANA.AC_Maquinaria,
TEMPANA.AC_Mano_Obra,
TEMPANA.AC_Medio_Ambiente,
TEMPANA.AC_Medicion,
TEMPANA.AC_Material,

CASE WHEN TEMPANA.rut_res_proc is null THEN 'Atributo no definido en hallazgo' else TEMPANA.rut_res_proc END rut_res_proc,

CASE WHEN TEMPANA.cargo_res_proc is null THEN 'Atributo no definido en hallazgo' else TEMPANA.cargo_res_proc END cargo_res_proc


FROM ( SELECT  /*+ optimizer_features_enable('9.2.0.8') */ 	
(SELECT FM0.identificador
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) identificador,


(SELECT FM0.fechadeteccion
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) fecha_deteccion,


(SELECT (select D0.iddepartment from ADDEPARTMENT D0 where D0.NMDEPARTMENT = FM0.dirregional) || ' - ' || FM0.dirregional 
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) dir_regional,

(SELECT FM0.idarea || ' - ' || FM0.area area
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) area_hall,

(SELECT FM0.nombreresproceso
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) nombre_res_proc,

(SELECT FM0.rutresproceso 
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) rut_res_proc,

(SELECT FM0.resproceso 
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) cargo_res_proc,

(SELECT FM0.nomquiendetecta 
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID )  
WHERE A.IDOBJECT = P.IDOBJECT) nombre_quien_detec,


(SELECT dbms_lob.substr(FM0.deschallazgo,4000,1) 
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) desc_hallazgo,


(SELECT FMCOMBO0.REQUISITONORMATI
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
LEFT OUTER JOIN DYNREQUISITOSNORMA FMCOMBO0 ON (FM0.OIDABC3sKABCQFw = FMCOMBO0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) req_normativo,

(SELECT FMCOMBO0.MACROPROCESO
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID )  
LEFT OUTER JOIN DYNMACROPROCESO FMCOMBO0 ON (FM0.OIDABCrRwABCBCx = FMCOMBO0.OID )
WHERE A.IDOBJECT = P.IDOBJECT) macroproceso,


(SELECT FMCOMBO0.PROCESO
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
LEFT OUTER JOIN DYNPROCESO FMCOMBO0 ON (FM0.OIDABCHZTABCPMS = FMCOMBO0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) proceso,

/**
(SELECT FMCOMBO0.SUPROCESO
FROM WFPROCESS A 
LEFT OUTER JOIN GNFORMREGGROUP B ON (A.CDFORMREGGROUP = B.CDFORMREGGROUP )
LEFT OUTER JOIN GNFORMREG C ON (B.CDFORMREGGROUP = C.CDFORMREGGROUP )
LEFT OUTER JOIN DYNFORMGH FM0 ON (C.OIDENTITYREG = FM0.OID ) 
LEFT OUTER JOIN DYNSUBPROCESO FMCOMBO0 ON (FM0.OIDABC53JABCOBI = FMCOMBO0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) subproceso,
**/

(SELECT CASE when FM0.fuenteorigen = 1 then 'Supervisión' when FM0.fuenteorigen = 2 then 'Auditoría Interna de Calidad' 
when FM0.fuenteorigen = 3 then 'Auditoría Externa de Calidad' when FM0.fuenteorigen = 4 then 'Personal SAG' 
when FM0.fuenteorigen = 5 then 'Clientes' ELSE 'Sin seleccionar' END 
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) fuente_origen,

(SELECT FM0.cargoresp1
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) cargo_resp_acc_1,

(SELECT FM0.nombrecargo1
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID )  
WHERE A.IDOBJECT = P.IDOBJECT) resp_acc_1,


(SELECT FM0.plazo1
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) plazo_acc_1,


(SELECT FM0.compromiso1
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) comp_acc_1,

(SELECT FM0.accionejecutada1
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) ejecucion_acc_1,


(SELECT FM0.cargoresp2
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) cargo_resp_acc_2,

(SELECT FM0.nombrecargo2
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) resp_acc_2,


(SELECT FM0.plazo2
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) plazo_acc_2,


(SELECT FM0.compromiso2
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) comp_acc_2,

(SELECT FM0.accionejecutada2
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) ejecucion_acc_2,


(SELECT FM0.cargoresp3
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) cargo_resp_acc_3,

(SELECT FM0.nombrecargo3
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) resp_acc_3,


(SELECT FM0.plazo3
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) plazo_acc_3,


(SELECT FM0.compromiso3
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) comp_acc_3,

(SELECT FM0.accionejecutada3
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) ejecucion_acc_3,


(SELECT FM0.cargoresp4
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) cargo_resp_acc_4,

(SELECT FM0.nombrecargo4
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) resp_acc_4,


(SELECT FM0.plazo4
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) plazo_acc_4,


(SELECT FM0.compromiso4
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) comp_acc_4,

(SELECT FM0.accionejecutada4
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) ejecucion_acc_4,

(SELECT FM0.cargoresp5
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) cargo_resp_acc_5,

(SELECT FM0.nombrecargo5
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID )  
WHERE A.IDOBJECT = P.IDOBJECT) resp_acc_5,


(SELECT FM0.plazo5
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) plazo_acc_5,


(SELECT FM0.compromiso5
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) comp_acc_5,

(SELECT FM0.accionejecutada5
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) ejecucion_acc_5,

(SELECT FM0.desccausametodo
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) AC_Metodo,

(SELECT FM0.desccausamaquina
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) AC_Maquinaria,

(SELECT FM0.desccausamanodeo
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) AC_Mano_Obra,

(SELECT FM0.desccausamedioam
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) AC_Medio_Ambiente,

(SELECT FM0.desccausamedicio
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) AC_Medicion,

(SELECT FM0.desccausamateria
FROM WFPROCESS A 
LEFT OUTER JOIN GNASSOCFORMREG B ON A.CDASSOCREG = B.CDASSOC
LEFT OUTER JOIN DYNFORMGH FM0 ON (B.OIDENTITYREG = FM0.OID ) 
WHERE A.IDOBJECT = P.IDOBJECT) AC_Material,



	P.CDPROCESS,		
	P.IDOBJECT,         
	P.IDPROCESS as id_hallazgo,        
	P.NMPROCESSMODEL as nombre_proceso,   
	P.NMPROCESS as titulo_hallazgo,        
	1 AS cantidad,	  	
	P.NMUSERSTART,	  	
	GNR.NMEVALRESULT,	
        incid.dsoccurrence,

                CASE P.FGSTATUS
                        WHEN 1 THEN 'En marcha'  
                        WHEN 2 THEN 'Suspendido'  
                        WHEN 3 THEN 'Cancelado'
                        WHEN 4 THEN 'Cerrado'
                        WHEN 5 THEN 'Bloqueado para edición'
                        END  AS estado_proceso,
                CASE WHEN P.FGCONCLUDEDSTATUS = 2
                     THEN 3
                     WHEN P.FGCONCLUDEDSTATUS = 1
                     THEN 1
                     WHEN VLTIMEFINISH = -1
                     THEN -1
                     WHEN (    ( P.DTESTIMATEDFINISH > CAST( SYSDATE+1 AS DATE) )
                            OR ( P.DTESTIMATEDFINISH IS NULL ) )
                     THEN 1
                     WHEN (    (     P.DTESTIMATEDFINISH = CAST( SYSDATE AS DATE) 
                                 AND P.NRTIMEESTFINISH >= (TO_CHAR(SYSDATE,'HH24') * 60)+(TO_CHAR(SYSDATE,'mi')) )
                            OR ( P.DTESTIMATEDFINISH = CAST( SYSDATE+1 AS DATE) ) )
                     THEN 2
                     ELSE 3
                 END AS FGDEADLINE
              , CASE WHEN P.FGCONCLUDEDSTATUS = 2
                     THEN 'Finalizado con atraso'
                     WHEN P.FGCONCLUDEDSTATUS = 1
                     THEN 'Finalizado dentro del plazo'
                     WHEN VLTIMEFINISH = -1
                     THEN 'Indeterminado'
                     WHEN (    ( P.DTESTIMATEDFINISH > CAST( SYSDATE+1 AS DATE) )
                            OR ( P.DTESTIMATEDFINISH IS NULL ) )
                     THEN 'Al día'
                     WHEN (    (     P.DTESTIMATEDFINISH = CAST( SYSDATE AS DATE) 
                                 AND P.NRTIMEESTFINISH >= (TO_CHAR(SYSDATE,'HH24') * 60)+(TO_CHAR(SYSDATE,'mi')) )
                            OR ( P.DTESTIMATEDFINISH = CAST( SYSDATE+1 AS DATE) ) )
                     THEN 'Próximo del vencimiento'
                     ELSE 'Atrasado'
                 END AS NMDEADLINE ,TO_CHAR(CAST(TRUNC(P.QTHOURS/1440) AS VARCHAR(20)),'0000') || ' día(s) ' || 
TO_CHAR(CAST(TRUNC((P.QTHOURS-(TRUNC(P.QTHOURS/1440)*1440))/60) AS VARCHAR(20)),'00') || ' hora(s) ' || 
TO_CHAR(CAST(P.QTHOURS-(TRUNC(P.QTHOURS/60)*60) AS VARCHAR(20)) ,'00') || ' minuto(s)' 
AS QTHOURS, 
CASE 
  WHEN  P.QTDURATION < 60 THEN P.QTDURATION || ' minuto(s)'
  WHEN  P.QTDURATION BETWEEN 60 AND 1440 THEN TRUNC((P.QTDURATION/60), 2) || ' hora(s)'
  WHEN  1440 < P.QTDURATION THEN TRUNC((P.QTDURATION/1440), 2) || ' día(s)'
END AS QTDURATION, 

CASE
WHEN P.FGSTATUS IN (1,2,3,5) THEN 
(
  TO_CHAR(TRUNC(SYSDATE - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss')), '0000') || ' día(s) ' ||
  TO_CHAR(TRUNC(((SYSDATE - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss')) 
  - TRUNC( (SYSDATE - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss'))))*24), '00') || ' hora(s) ' ||
  TO_CHAR(TRUNC(((((SYSDATE - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss')) 
  - TRUNC((SYSDATE - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss'))))*24) - TRUNC(((SYSDATE - TO_DATE(TO_CHAR

(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss')) 
  - TRUNC((SYSDATE - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss'))))*24))*60 ), '00') || ' minuto(s)' 
)
WHEN P.FGSTATUS = 4 THEN  
(
    TO_CHAR(TRUNC(TO_DATE(TO_CHAR(P.DTFINISH, 'dd/mm/yyyy') ||' '||P.TMFINISH, 'dd/mm/yyyy hh24:mi:ss')
    - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss')), '0000') || ' día(s) ' ||
    TO_CHAR(TRUNC(((TO_DATE(TO_CHAR(P.DTFINISH, 'dd/mm/yyyy') ||' '||P.TMFINISH, 'dd/mm/yyyy hh24:mi:ss')
    - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss'))
    - TRUNC( (TO_DATE(TO_CHAR(P.DTFINISH, 'dd/mm/yyyy') ||' '||P.TMFINISH, 'dd/mm/yyyy hh24:mi:ss')
    - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss')) ))*24), '00') || ' hora(s) ' ||
    TO_CHAR(TRUNC(((((TO_DATE(TO_CHAR(P.DTFINISH, 'dd/mm/yyyy') ||' '||P.TMFINISH, 'dd/mm/yyyy hh24:mi:ss')
    - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss')) 
    - TRUNC((TO_DATE(TO_CHAR(P.DTFINISH, 'dd/mm/yyyy') ||' '||P.TMFINISH, 'dd/mm/yyyy hh24:mi:ss')
    - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss')) ))*24) 
    - TRUNC(((TO_DATE(TO_CHAR(P.DTFINISH, 'dd/mm/yyyy') ||' '||P.TMFINISH, 'dd/mm/yyyy hh24:mi:ss')
    - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss')) 
    - TRUNC((TO_DATE(TO_CHAR(P.DTFINISH, 'dd/mm/yyyy') ||' '||P.TMFINISH, 'dd/mm/yyyy hh24:mi:ss') 
    - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy') ||' '||P.TMSTART, 'dd/mm/yyyy hh24:mi:ss'))))*24))*60 ), '00') ||' minuto(s)'
)	
END AS DURATION_WF , 	
P.DTSTART AS DTSTART, 
TO_CHAR(P.DTSTART, 'YYYY') AS DTSTART_YEAR, 
TO_CHAR(P.DTSTART, 'MM') AS DTSTART_MONTH,
P.DTFINISH AS DTFINISH ,
ROUND(SYSDATE - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy'), 'dd/mm/yyyy'))  AS DAYS_FROM_START,
ROUND(SYSDATE - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy'), 'dd/mm/yyyy'))  AS DIAS_DESDE_INICIO,
ROUND(SYSDATE - TO_DATE(TO_CHAR(P.DTSTART, 'dd/mm/yyyy'), 'dd/mm/yyyy'))  AS NUM_DIAS_DESDE_INICIO

, GNT.NMGENTYPE AS tipo_hallazgo, GNRS.IDREVISIONSTATUS AS estado_hallazgo, GNRS.NMREVISIONSTATUS AS situacion_hallazgo  FROM  WFPROCESS P INNER 

JOIN PMACTIVITY PP ON PP.CDACTIVITY = P.CDPROCESSMODEL 
							 INNER JOIN PMACTTYPE PT ON PT.CDACTTYPE = PP.CDACTTYPE 
  LEFT OUTER JOIN GNACTIVITY GNA ON (P.CDGENACTIVITY = GNA.CDGENACTIVITY) 
							 LEFT OUTER JOIN GNEVALRESULTUSED GNRUS ON (GNRUS.CDEVALRESULTUSED = GNA.CDEVALRSLTPRIORITY)
							 LEFT OUTER JOIN GNEVALRESULT GNR ON (GNRUS.CDEVALRESULT = GNR.CDEVALRESULT) 
							 LEFT OUTER JOIN GNREVISION GREV ON P.CDREVISION = GREV.CDREVISION 
							 

				LEFT OUTER JOIN (SELECT  CASE WHEN COUNT(GNASSOC.CDACCESSLIST) = SUM(GNLIST.FGPERMISSION) THEN 1 ELSE 0 END AS 

FGPERM, WFP.IDOBJECT  FROM  PMACTTYPESECURLIST GNLIST
						INNER JOIN PMACTTYPESECURCTRL GNASSOC ON GNLIST.CDACCESSLIST = GNASSOC.CDACCESSLIST AND 

GNLIST.CDACTTYPE = GNASSOC.CDACTTYPE
						INNER JOIN PMACCESSROLEFIELD GNCTRL ON GNASSOC.CDACCESSROLEFIELD = GNCTRL.CDACCESSROLEFIELD
						INNER JOIN PMACCESSROLEFIELD GNCTRL_F ON GNCTRL.CDRELATEDFIELD = GNCTRL_F.CDACCESSROLEFIELD
						INNER JOIN PMACTIVITY PMA ON GNLIST.CDACTTYPE = PMA.CDACTTYPE
						INNER JOIN WFPROCESS WFP ON PMA.CDACTIVITY = WFP.CDPROCESSMODEL 
 LEFT JOIN ADUSERDEPTPOS UDP_DEP ON (UDP_DEP.CDDEPARTMENT = GNLIST.CDDEPARTMENT AND UDP_DEP.CDUSER = 831) 
					LEFT JOIN ADUSERDEPTPOS UDP_DEPPOS ON (UDP_DEPPOS.CDDEPARTMENT = GNLIST.CDDEPARTMENT AND 

UDP_DEPPOS.CDPOSITION   = GNLIST.CDPOSITION 
						AND UDP_DEPPOS.CDUSER = 831)
					LEFT JOIN ADUSERDEPTPOS UDP_POS ON (UDP_POS.CDPOSITION = GNLIST.CDPOSITION AND UDP_POS.CDUSER = 831)
					LEFT JOIN ADUSERROLE USR ON (USR.CDROLE = GNLIST.CDROLE AND USR.CDUSER = 831)
					LEFT JOIN (
						SELECT CDTEAM FROM ADTEAMMEMBER  WHERE FGTEAMMEMBER = 4 AND CDUSER = 831
						UNION ALL
						SELECT CDTEAM
						FROM ADTEAMMEMBER TM,  ADUSERDEPTPOS UDP
						WHERE UDP.CDUSER = 831 
							AND
							(
								(TM.FGTEAMMEMBER = 1 AND TM.CDDEPARTMENT = UDP.CDDEPARTMENT)
								OR (TM.FGTEAMMEMBER = 2 AND TM.CDPOSITION = UDP.CDPOSITION)
								OR (TM.FGTEAMMEMBER = 3 AND TM.CDDEPARTMENT = UDP.CDDEPARTMENT AND TM.CDPOSITION = 

UDP.CDPOSITION)
							)
						) TEAM ON TEAM.CDTEAM = GNLIST.CDTEAM 
 LEFT JOIN ADUSER US ON (US.CDUSER = WFP.CDUSERSTART AND US.CDLEADER = 831) 
 WHERE  GNCTRL_F.CDRELATEDFIELD  = 501
						AND PMA.FGUSETYPEACCESS = 1 
 AND WFP.FGMODELWFSECURITY = 1  AND ( GNLIST.FGACCESSTYPE = 6
					   OR (GNLIST.FGACCESSTYPE = 1  AND TEAM.CDTEAM IS NOT NULL )
					   OR (GNLIST.FGACCESSTYPE = 2  AND UDP_DEP.CDUSER IS NOT NULL)
					   OR (GNLIST.FGACCESSTYPE = 3  AND UDP_DEPPOS.CDUSER IS NOT NULL)
					   OR (GNLIST.FGACCESSTYPE = 4  AND UDP_POS.CDUSER IS NOT NULL)
					   OR (GNLIST.FGACCESSTYPE = 5  AND GNLIST.CDUSER = 831)
					   OR (GNLIST.FGACCESSTYPE = 7  AND USR.CDROLE IS NOT NULL ) 
 OR  (GNLIST.FGACCESSTYPE = 30 AND WFP.CDUSERSTART = 831)
				OR (GNLIST.FGACCESSTYPE = 31 AND US.CDUSER IS NOT NULL) 
 
						OR
						(
							GNLIST.FGACCESSTYPE = 9 AND EXISTS (SELECT 1 FROM ADUSERDEPTPOS ADUDP WHERE ADUDP.CDUSER = 

831
								AND EXISTS (SELECT 1 FROM ADUSERDEPTPOS WHERE CDUSER = PMA.CDCREATEDBY AND 

CDDEPARTMENT = ADUDP.CDDEPARTMENT))
						)
						OR
						(
							GNLIST.FGACCESSTYPE = 10 AND EXISTS (SELECT 1 FROM ADUSERDEPTPOS ADUDP WHERE ADUDP.CDUSER = 

831
								AND EXISTS (SELECT 1 FROM ADUSERDEPTPOS WHERE CDUSER = PMA.CDCREATEDBY AND 

CDDEPARTMENT = ADUDP.CDDEPARTMENT AND CDPOSITION = ADUDP.CDPOSITION))
						)
						OR
						(
							GNLIST.FGACCESSTYPE = 11 AND EXISTS (SELECT 1 FROM ADUSERDEPTPOS ADUDP WHERE ADUDP.CDUSER = 

831
								AND EXISTS (SELECT 1 FROM ADUSERDEPTPOS WHERE CDUSER = PMA.CDCREATEDBY AND 

CDPOSITION = ADUDP.CDPOSITION))
						)
						OR (GNLIST.FGACCESSTYPE = 12 AND EXISTS (SELECT 1 FROM ADUSER WHERE CDUSER = PMA.CDCREATEDBY AND 

CDLEADER = 831)) 
) 
 GROUP BY  PMA.CDACTIVITY,  WFP.IDOBJECT ) SECPROCTP_1 ON (P.IDOBJECT = SECPROCTP_1.IDOBJECT)
				LEFT OUTER JOIN (SELECT  CASE WHEN COUNT(GNASSOC.CDACCESSLIST) = SUM(GNLIST.FGPERMISSION) THEN 1 ELSE -1 END AS 

FGPERM,  GNLIST.CDPROC FROM  PMPROCACCESSLIST GNLIST 
						INNER JOIN PMPROCSECURITYCTRL GNASSOC ON GNLIST.CDACCESSLIST = GNASSOC.CDACCESSLIST AND 

GNLIST.CDPROC = GNASSOC.CDPROC
						INNER JOIN PMACCESSROLEFIELD GNCTRL ON GNASSOC.CDACCESSROLEFIELD = GNCTRL.CDACCESSROLEFIELD
						INNER JOIN PMACTIVITY OBJ ON GNASSOC.CDPROC = OBJ.CDACTIVITY 
 LEFT JOIN ADUSERDEPTPOS UDP_DEP ON (UDP_DEP.CDDEPARTMENT = GNLIST.CDDEPARTMENT AND UDP_DEP.CDUSER = 831) 
					LEFT JOIN ADUSERDEPTPOS UDP_DEPPOS ON (UDP_DEPPOS.CDDEPARTMENT = GNLIST.CDDEPARTMENT AND 

UDP_DEPPOS.CDPOSITION   = GNLIST.CDPOSITION 
						AND UDP_DEPPOS.CDUSER = 831)
					LEFT JOIN ADUSERDEPTPOS UDP_POS ON (UDP_POS.CDPOSITION = GNLIST.CDPOSITION AND UDP_POS.CDUSER = 831)
					LEFT JOIN ADUSERROLE USR ON (USR.CDROLE = GNLIST.CDROLE AND USR.CDUSER = 831)
					LEFT JOIN (
						SELECT CDTEAM FROM ADTEAMMEMBER  WHERE FGTEAMMEMBER = 4 AND CDUSER = 831
						UNION ALL
						SELECT CDTEAM
						FROM ADTEAMMEMBER TM,  ADUSERDEPTPOS UDP
						WHERE UDP.CDUSER = 831 
							AND
							(
								(TM.FGTEAMMEMBER = 1 AND TM.CDDEPARTMENT = UDP.CDDEPARTMENT)
								OR (TM.FGTEAMMEMBER = 2 AND TM.CDPOSITION = UDP.CDPOSITION)
								OR (TM.FGTEAMMEMBER = 3 AND TM.CDDEPARTMENT = UDP.CDDEPARTMENT AND TM.CDPOSITION = 

UDP.CDPOSITION)
							)
						) TEAM ON TEAM.CDTEAM = GNLIST.CDTEAM 
 WHERE  GNCTRL.CDRELATEDFIELD  = 501
						AND (OBJ.FGUSETYPEACCESS = 0 OR OBJ.FGUSETYPEACCESS IS NULL) 
 AND ( GNLIST.FGACCESSTYPE = 6
					   OR (GNLIST.FGACCESSTYPE = 1  AND TEAM.CDTEAM IS NOT NULL )
					   OR (GNLIST.FGACCESSTYPE = 2  AND UDP_DEP.CDUSER IS NOT NULL)
					   OR (GNLIST.FGACCESSTYPE = 3  AND UDP_DEPPOS.CDUSER IS NOT NULL)
					   OR (GNLIST.FGACCESSTYPE = 4  AND UDP_POS.CDUSER IS NOT NULL)
					   OR (GNLIST.FGACCESSTYPE = 5  AND GNLIST.CDUSER = 831)
					   OR (GNLIST.FGACCESSTYPE = 7  AND USR.CDROLE IS NOT NULL ) 
) 
 GROUP BY  GNLIST.CDPROC ) SECPROC_1_1 ON (SECPROC_1_1.CDPROC = P.CDPROCESSMODEL)
				LEFT OUTER JOIN (SELECT  CASE WHEN COUNT(GNASSOC.CDACCESSLIST) = SUM(GNLIST.FGPERMISSION) THEN 1 ELSE -1 END AS 

FGPERM,  GNLIST.CDPROC,  WFP.IDOBJECT  FROM  PMPROCACCESSLIST GNLIST 
						INNER JOIN PMPROCSECURITYCTRL GNASSOC ON GNLIST.CDACCESSLIST = GNASSOC.CDACCESSLIST AND 

GNLIST.CDPROC = GNASSOC.CDPROC
						INNER JOIN PMACCESSROLEFIELD GNCTRL ON GNASSOC.CDACCESSROLEFIELD = GNCTRL.CDACCESSROLEFIELD
						INNER JOIN PMACTIVITY OBJ ON GNASSOC.CDPROC = OBJ.CDACTIVITY
						INNER JOIN WFPROCESS WFP ON WFP.CDPROCESSMODEL = GNASSOC.CDPROC 
 LEFT JOIN ADUSER US ON (US.CDUSER = WFP.CDUSERSTART AND US.CDLEADER = 831) 
 WHERE  GNCTRL.CDRELATEDFIELD  = 501
						AND (OBJ.FGUSETYPEACCESS = 0 OR OBJ.FGUSETYPEACCESS IS NULL) 
 AND WFP.FGMODELWFSECURITY = 1  AND ( (GNLIST.FGACCESSTYPE = 30 AND WFP.CDUSERSTART = 831)
				OR (GNLIST.FGACCESSTYPE = 31 AND US.CDUSER IS NOT NULL) 
) 
 GROUP BY  GNLIST.CDPROC,  WFP.IDOBJECT ) SECPROC_2_1 ON (SECPROC_2_1.CDPROC = P.CDPROCESSMODEL AND SECPROC_2_1.IDOBJECT = P.IDOBJECT)
				LEFT OUTER JOIN (SELECT  CASE WHEN COUNT(GNASSOC.CDACCESSLIST) = SUM(GNLIST.FGPERMISSION) THEN 1 ELSE NULL END AS 

FGPERM,  GNASSOC.IDPROCESS  FROM  WFPROCSECURITYLIST GNLIST 
						INNER JOIN WFPROCSECURITYCTRL GNASSOC ON GNLIST.CDACCESSLIST = GNASSOC.CDACCESSLIST AND 

GNLIST.IDPROCESS = GNASSOC.IDPROCESS
						INNER JOIN WFPROCESS WFP ON GNASSOC.IDPROCESS = WFP.IDOBJECT 
 LEFT JOIN ADUSERDEPTPOS UDP_DEP ON (UDP_DEP.CDDEPARTMENT = GNLIST.CDDEPARTMENT AND UDP_DEP.CDUSER = 831) 
					LEFT JOIN ADUSERDEPTPOS UDP_DEPPOS ON (UDP_DEPPOS.CDDEPARTMENT = GNLIST.CDDEPARTMENT AND 

UDP_DEPPOS.CDPOSITION   = GNLIST.CDPOSITION 
						AND UDP_DEPPOS.CDUSER = 831)
					LEFT JOIN ADUSERDEPTPOS UDP_POS ON (UDP_POS.CDPOSITION = GNLIST.CDPOSITION AND UDP_POS.CDUSER = 831)
					LEFT JOIN ADUSERROLE USR ON (USR.CDROLE = GNLIST.CDROLE AND USR.CDUSER = 831)
					LEFT JOIN (
						SELECT CDTEAM FROM ADTEAMMEMBER  WHERE FGTEAMMEMBER = 4 AND CDUSER = 831
						UNION ALL
						SELECT CDTEAM
						FROM ADTEAMMEMBER TM,  ADUSERDEPTPOS UDP
						WHERE UDP.CDUSER = 831 
							AND
							(
								(TM.FGTEAMMEMBER = 1 AND TM.CDDEPARTMENT = UDP.CDDEPARTMENT)
								OR (TM.FGTEAMMEMBER = 2 AND TM.CDPOSITION = UDP.CDPOSITION)
								OR (TM.FGTEAMMEMBER = 3 AND TM.CDDEPARTMENT = UDP.CDDEPARTMENT AND TM.CDPOSITION = 

UDP.CDPOSITION)
							)
						) TEAM ON TEAM.CDTEAM = GNLIST.CDTEAM 
 LEFT JOIN ADUSER US ON (US.CDUSER = WFP.CDUSERSTART AND US.CDLEADER = 831) 
 WHERE  (WFP.FGMODELWFSECURITY IS NULL OR WFP.FGMODELWFSECURITY = 0) AND GNASSOC.CDACCESSROLEFIELD  = 501 AND ( GNLIST.FGACCESSTYPE = 6
					   OR (GNLIST.FGACCESSTYPE = 1  AND TEAM.CDTEAM IS NOT NULL )
					   OR (GNLIST.FGACCESSTYPE = 2  AND UDP_DEP.CDUSER IS NOT NULL)
					   OR (GNLIST.FGACCESSTYPE = 3  AND UDP_DEPPOS.CDUSER IS NOT NULL)
					   OR (GNLIST.FGACCESSTYPE = 4  AND UDP_POS.CDUSER IS NOT NULL)
					   OR (GNLIST.FGACCESSTYPE = 5  AND GNLIST.CDUSER = 831)
					   OR (GNLIST.FGACCESSTYPE = 7  AND USR.CDROLE IS NOT NULL ) 
 OR  (GNLIST.FGACCESSTYPE = 30 AND WFP.CDUSERSTART = 831)
				OR (GNLIST.FGACCESSTYPE = 31 AND US.CDUSER IS NOT NULL) 
) 
 GROUP BY  GNASSOC.IDPROCESS ) SECWFPROC_1 ON (SECWFPROC_1.IDPROCESS = P.IDOBJECT)
				 LEFT OUTER JOIN INOCCURRENCE INCID ON (P.IDOBJECT = INCID.IDWORKFLOW) 
							LEFT OUTER JOIN GNGENTYPE GNT ON (INCID.CDOCCURRENCETYPE = GNT.CDGENTYPE) 
							LEFT OUTER JOIN GNREVISIONSTATUS GNRS ON (INCID.CDSTATUS = GNRS.CDREVISIONSTATUS) 
							 INNER JOIN PBPROBLEM PB ON PB.CDOCCURRENCE = INCID.CDOCCURRENCE  WHERE  P.FGSTATUS <= 5    

AND  (GNT.CDTYPEROLE IS NULL OR (EXISTS (SELECT 1 FROM GNTYPEROLE GNROLE_ALIAS WHERE GNROLE_ALIAS.CDTYPEROLE = GNT.CDTYPEROLE AND 

GNROLE_ALIAS.FGTYPE = 1)) OR ( EXISTS (SELECT 1 FROM GNTYPEPERMISSION GNROLEDEF_ALIAS WHERE GNROLEDEF_ALIAS.CDTYPEROLE = GNT.CDTYPEROLE AND 

GNROLEDEF_ALIAS.CDACCESSLIST = 1 AND GNROLEDEF_ALIAS.CDUSER = 831 ))) AND 
				(
					(
						(
							(PP.FGUSETYPEACCESS = 1 AND SECPROCTP_1.FGPERM = 1)
							OR
							(
								(PP.FGUSETYPEACCESS = 0 OR PP.FGUSETYPEACCESS IS NULL) AND 
								(
									(SECPROC_1_1.FGPERM = 1 AND (SECPROC_2_1.FGPERM IS NULL OR 

SECPROC_2_1.FGPERM <> -1))
									OR (SECPROC_2_1.FGPERM = 1 AND (SECPROC_1_1.FGPERM IS NULL OR 

SECPROC_1_1.FGPERM <> -1))
								)
							)
						)
						AND P.FGMODELWFSECURITY = 1
					)
					OR ((P.FGMODELWFSECURITY IS NULL OR P.FGMODELWFSECURITY = 0) AND SECWFPROC_1.FGPERM = 1)
				)
 AND INCID.FGOCCURRENCETYPE = 2 ) TEMPANA ) TEMP2 LEFT JOIN (SELECT
        IDPROCESS,
        NMPROCESS,
        NMPROCESSMODEL,
        NMSTRUCT,
        NMUSER,
		CDUSER,
        TYPEUSEREXEC,
        NMROLE,
        NMEXECUTEDACTION,
        DTEXECUTION,
        IDSITUATION,
        NMEVALRESULT,
        NMUSERSTART,
        TYPEUSER,
        DTDEADLINEFIELD,

        NMOCCURRENCETYPE,
		IDSTRUCT
    FROM
        (SELECT
            IDPROCESS,
            NMPROCESS,
            NMPROCESSMODEL,
            NMSTRUCT,
            NMUSER,
		 	CDUSER,
            TYPEUSEREXEC,
            NMROLE,
            NMEXECUTEDACTION,
            DTEXECUTION,
            IDSITUATION,
            NMEVALRESULT,
            NMUSERSTART,
            TYPEUSER,
            DTDEADLINEFIELD,

            NMOCCURRENCETYPE,
		 	IDSTRUCT
        FROM
            (SELECT
                1 AS QTD,
                WFP.IDPROCESS,
                WFP.NMPROCESS,
                COALESCE(PML.NMPROCESS,
                WFP.NMPROCESSMODEL) AS NMPROCESSMODEL,
                COALESCE(ADU.NMUSER,
                TBEXT.NMUSER) AS NMUSERSTART,
		WFA.CDUSER CDUSER,
                CASE 
                    WHEN WFP.CDEXTERNALUSERSTART IS NOT NULL THEN '#{303826}' 
                    WHEN WFP.CDUSERSTART IS NOT NULL THEN '#{305843}' 
                    ELSE NULL 
                END AS TYPEUSER,
                GNT.NMGENTYPE AS NMOCCURRENCETYPE,
                GNR.NMEVALRESULT,
                COALESCE(PMEL.NMELEMENT,
                WFS.NMSTRUCT) AS NMSTRUCT,
                WFA.NMROLE,
                CASE 
                    WHEN WFS.FGSTATUS=1 THEN '#{114667}' 
                    WHEN WFS.FGSTATUS=2 THEN '#{114666}' 
                    WHEN WFS.FGSTATUS=3 THEN '#{107507}' 
                    WHEN WFS.FGSTATUS=4 THEN '#{108240}' 
                    WHEN WFS.FGSTATUS=5 THEN '#{102338}' 
                    WHEN WFS.FGSTATUS=6 THEN '#{206049}' 
                    WHEN WFS.FGSTATUS=7 THEN '#{214511}' 
                END AS IDSITUATION,
                WFS.DTEXECUTION,
                CASE 
                    WHEN WFA.FGACTAUTOEXECUTED=1 THEN '#{102949}' 
                    ELSE WFA.NMUSER 
                END AS NMUSER,
                CASE 
                    WHEN WFA.CDEXTERNALUSER IS NOT NULL THEN '#{303826}' 
                    WHEN WFA.CDUSER IS NOT NULL 
                    AND WFA.NMUSER IS NOT NULL THEN '#{305843}' 
                    ELSE NULL 
                END AS TYPEUSEREXEC,
                COALESCE(PMAL.NMACTION,
                WFA.NMEXECUTEDACTION) AS NMEXECUTEDACTION,
                WFS.DTESTIMATEDFINISH + WFS.NRTIMEESTFINISH/1440 AS DTDEADLINEFIELD, 
			 	WFS.IDSTRUCT
            FROM
                WFPROCESS WFP 
            INNER JOIN
                WFSTRUCT WFS 
                    ON WFS.IDPROCESS=WFP.IDOBJECT 
            INNER JOIN
                WFACTIVITY WFA 
                    ON WFS.IDOBJECT=WFA.IDOBJECT 
            LEFT OUTER JOIN
                PMACTIVITY PP 
                    ON PP.CDACTIVITY=WFP.CDPROCESSMODEL 
            LEFT OUTER JOIN
                PMACTTYPE PT 
                    ON PT.CDACTTYPE=PP.CDACTTYPE 
            LEFT OUTER JOIN
                GNREVISION GNREV 
                    ON WFP.CDREVISION=GNREV.CDREVISION 
            LEFT OUTER JOIN
                ADUSER ADU 
                    ON ADU.CDUSER=WFP.CDUSERSTART 
            LEFT OUTER JOIN
                (
                    SELECT
                        ADEXTERNALUSER.CDEXTERNALUSER,
                        ADCOMPANY.NMCOMPANY,
                        ADEXTERNALUSER.NMUSER 
                    FROM
                        ADEXTERNALUSER 
                    INNER JOIN
                        ADCOMPANY 
                            ON ADEXTERNALUSER.CDCOMPANY=ADCOMPANY.CDCOMPANY
                    ) TBEXT 
                        ON WFP.CDEXTERNALUSERSTART=TBEXT.CDEXTERNALUSER 
                LEFT OUTER JOIN
                    GNSLACONTROL SLACTRL 
                        ON WFP.CDSLACONTROL=SLACTRL.CDSLACONTROL 
                LEFT OUTER JOIN
                    GNREVISIONSTATUS GNRS 
                        ON WFP.CDSTATUS=GNRS.CDREVISIONSTATUS 
                LEFT OUTER JOIN
                    GNEVALRESULTUSED GNRUS 
                        ON GNRUS.CDEVALRESULTUSED=WFP.CDEVALRSLTPRIORITY 
                LEFT OUTER JOIN
                    GNEVALRESULT GNR 
                        ON GNRUS.CDEVALRESULT=GNR.CDEVALRESULT 
                LEFT OUTER JOIN
                    INOCCURRENCE INOCCUR 
                        ON WFP.IDOBJECT=INOCCUR.IDWORKFLOW 
                LEFT OUTER JOIN
                    GNGENTYPE GNT 
                        ON INOCCUR.CDOCCURRENCETYPE=GNT.CDGENTYPE 
                INNER JOIN
                    PMACTREVISION PMACT 
                        ON (
                            PMACT.CDACTIVITY=WFP.CDPROCESSMODEL 
                            AND PMACT.CDREVISION=WFP.CDREVISION
                        ) 
                LEFT JOIN
                    PMPROCESSLANGUAGE PML 
                        ON (
                            PML.CDPROCESS=PMACT.CDACTIVITY 
                            AND PML.CDREVISION=PMACT.CDREVISION 
                            AND PML.FGLANGUAGE=3 
                            AND PML.FGENABLED=1
                        ) 
                LEFT OUTER JOIN
                    PMELEMENTLANGUAGE PMEL 
                        ON (
                            PMEL.CDSTRUCT=WFS.CDSTRUCTMODEL 
                            AND PMEL.FGLANGUAGE=3 
                            AND EXISTS (
                                SELECT
                                    1 
                            FROM
                                PMPROCESSLANGUAGE PML 
                            WHERE
                                PMACT.CDACTIVITY=PML.CDPROCESS 
                                AND PMACT.CDREVISION=PML.CDREVISION 
                                AND PML.FGLANGUAGE=3 
                                AND PML.FGENABLED=1
                        )
                    ) 
                LEFT OUTER JOIN
                    WFSTRUCTACTION WFSA 
                        ON WFSA.IDOBJECT=WFA.IDEXECUTEDACTION 
                LEFT OUTER JOIN
                    PMACTIONLANGUAGE PMAL 
                        ON (
                            PMAL.CDSTRUCT=WFSA.CDSTRUCTMODEL 
                            AND PMAL.CDACTION=WFSA.CDACTIONMODEL 
                            AND PMAL.FGLANGUAGE=3 
                            AND EXISTS (
                                SELECT
                                    1 
                            FROM
                                PMPROCESSLANGUAGE PML 
                            WHERE
                                PMACT.CDACTIVITY=PML.CDPROCESS 
                                AND PMACT.CDREVISION=PML.CDREVISION 
                                AND PML.FGLANGUAGE=3 
                                AND PML.FGENABLED=1
                        )
                    ) 
                INNER JOIN
                    (
                        SELECT
                            DISTINCT Z.IDOBJECT 
                        FROM
                            (SELECT
                                AUXWFP.IDOBJECT 
                            FROM
                                WFPROCESS AUXWFP 
                            INNER JOIN
                                (
                                    SELECT
                                        PERM.USERCD,
                                        PERM.IDPROCESS,
                                        MIN(PERM.FGPERMISSION) AS FGPERMISSION 
                                    FROM
                                        (SELECT
                                            WF.FGPERMISSION,
                                            WF.IDPROCESS,
                                            TM.CDUSER AS USERCD,
                                            WF.CDACCESSLIST 
                                        FROM
                                            WFPROCSECURITYLIST WF 
                                        INNER JOIN
                                            ADTEAMUSER TM 
                                                ON WF.CDTEAM=TM.CDTEAM 
                                        WHERE
                                            WF.FGACCESSTYPE=1 
                                            AND TM.CDUSER=831 
                                            AND WF.FGACCESSEXCEPTION IS NULL 
                                        UNION
                                        ALL SELECT
                                            WF.FGPERMISSION,
                                            WF.IDPROCESS,
                                            UDP.CDUSER AS USERCD,
                                            WF.CDACCESSLIST 
                                        FROM
                                            WFPROCSECURITYLIST WF 
                                        INNER JOIN
                                            ADUSERDEPTPOS UDP 
                                                ON WF.CDDEPARTMENT=UDP.CDDEPARTMENT 
                                        WHERE
                                            WF.FGACCESSTYPE=2 
                                            AND UDP.CDUSER=831 
                                            AND WF.FGACCESSEXCEPTION IS NULL 
                                        UNION
                                        ALL SELECT
                                            WF.FGPERMISSION,
                                            WF.IDPROCESS,
                                            UDP.CDUSER AS USERCD,
                                            WF.CDACCESSLIST 
                                        FROM
                                            WFPROCSECURITYLIST WF 
                                        INNER JOIN
                                            ADUSERDEPTPOS UDP 
                                                ON WF.CDDEPARTMENT=UDP.CDDEPARTMENT 
                                                AND WF.CDPOSITION=UDP.CDPOSITION 
                                        WHERE
                                            WF.FGACCESSTYPE=3 
                                            AND UDP.CDUSER=831 
                                            AND WF.FGACCESSEXCEPTION IS NULL 
                                        UNION
                                        ALL SELECT
                                            WF.FGPERMISSION,
                                            WF.IDPROCESS,
                                            UDP.CDUSER AS USERCD,
                                            WF.CDACCESSLIST 
                                        FROM
                                            WFPROCSECURITYLIST WF 
                                        INNER JOIN
                                            ADUSERDEPTPOS UDP 
                                                ON WF.CDPOSITION=UDP.CDPOSITION 
                                        WHERE
                                            WF.FGACCESSTYPE=4 
                                            AND UDP.CDUSER=831 
                                            AND WF.FGACCESSEXCEPTION IS NULL 
                                        UNION
                                        ALL SELECT
                                            WF.FGPERMISSION,
                                            WF.IDPROCESS,
                                            WF.CDUSER AS USERCD,
                                            WF.CDACCESSLIST 
                                        FROM
                                            WFPROCSECURITYLIST WF 
                                        WHERE
                                            WF.FGACCESSTYPE=5 
                                            AND WF.CDUSER=831 
                                            AND WF.FGACCESSEXCEPTION IS NULL 
                                        UNION
                                        ALL SELECT
                                            WF.FGPERMISSION,
                                            WF.IDPROCESS,
                                            US.CDUSER AS USERCD,
                                            WF.CDACCESSLIST 
                                        FROM
                                            WFPROCSECURITYLIST WF CROSS 
                                        JOIN
                                            ADUSER US 
                                        WHERE
                                            WF.FGACCESSTYPE=6 
                                            AND US.CDUSER=831 
                                            AND WF.FGACCESSEXCEPTION IS NULL 
                                        UNION
                                        ALL SELECT
                                            WF.FGPERMISSION,
                                            WF.IDPROCESS,
                                            RL.CDUSER AS USERCD,
                                            WF.CDACCESSLIST 
                                        FROM
                                            WFPROCSECURITYLIST WF 
                                        INNER JOIN
                                            ADUSERROLE RL 
                                                ON RL.CDROLE=WF.CDROLE 
                                        WHERE
                                            WF.FGACCESSTYPE=7 
                                            AND RL.CDUSER=831 
                                            AND WF.FGACCESSEXCEPTION IS NULL 
                                        UNION
                                        ALL SELECT
                                            WF.FGPERMISSION,
                                            WF.IDPROCESS,
                                            WFP.CDUSERSTART AS USERCD,
                                            WF.CDACCESSLIST 
                                        FROM
                                            WFPROCSECURITYLIST WF 
                                        INNER JOIN
                                            WFPROCESS WFP 
                                                ON WFP.IDOBJECT=WF.IDPROCESS 
                                        WHERE
                                            WF.FGACCESSTYPE=30 
                                            AND WFP.CDUSERSTART=831 
                                            AND WF.FGACCESSEXCEPTION IS NULL 
                                        UNION
                                        ALL SELECT
                                            WF.FGPERMISSION,
                                            WF.IDPROCESS,
                                            US.CDLEADER AS USERCD,
                                            WF.CDACCESSLIST 
                                        FROM
                                            WFPROCSECURITYLIST WF 
                                        INNER JOIN
                                            WFPROCESS WFP 
                                                ON WFP.IDOBJECT=WF.IDPROCESS 
                                        INNER JOIN
                                            ADUSER US 
                                                ON US.CDUSER=WFP.CDUSERSTART 
                                        WHERE
                                            WF.FGACCESSTYPE=31 
                                            AND US.CDLEADER=831 
                                            AND WF.FGACCESSEXCEPTION IS NULL
                                    ) PERM 
                                INNER JOIN
                                    WFPROCSECURITYCTRL GNASSOC 
                                        ON (
                                            GNASSOC.CDACCESSLIST=PERM.CDACCESSLIST 
                                            AND GNASSOC.IDPROCESS=PERM.IDPROCESS
                                        ) 
                                WHERE
                                    GNASSOC.CDACCESSROLEFIELD IN (
                                        501
                                    ) 
                                GROUP BY
                                    PERM.USERCD,
                                    PERM.IDPROCESS
                            ) PERMISSION 
                                ON PERMISSION.IDPROCESS=AUXWFP.IDOBJECT 
                        WHERE
                            PERMISSION.FGPERMISSION=1 
                            AND AUXWFP.FGSTATUS <= 5 
                            AND (
                                AUXWFP.FGMODELWFSECURITY IS NULL 
                                OR AUXWFP.FGMODELWFSECURITY=0
                            ) 
                            AND AUXWFP.CDPRODAUTOMATION IN (
                                160,202
                            ) 
                        UNION
                        ALL SELECT
                            T.IDOBJECT 
                        FROM
                            (SELECT
                                MIN(PERM99.FGPERMISSION) AS FGPERMISSION,
                                PERM99.IDOBJECT 
                            FROM
                                (SELECT
                                    WFP.IDOBJECT,
                                    PERM1.FGPERMISSION 
                                FROM
                                    (SELECT
                                        PP.FGPERMISSION,
                                        PP.CDPROC,
                                        PP.CDACCESSLIST,
                                        TM.CDUSER AS USERCD 
                                    FROM
                                        PMPROCACCESSLIST PP 
                                    INNER JOIN
                                        ADTEAMUSER TM 
                                            ON PP.CDTEAM=TM.CDTEAM 
                                    WHERE
                                        PP.FGACCESSTYPE=1 
                                        AND TM.CDUSER=831 
                                    UNION
                                    ALL SELECT
                                        PP.FGPERMISSION,
                                        PP.CDPROC,
                                        PP.CDACCESSLIST,
                                        UDP.CDUSER AS USERCD 
                                    FROM
                                        PMPROCACCESSLIST PP 
                                    INNER JOIN
                                        ADUSERDEPTPOS UDP 
                                            ON PP.CDDEPARTMENT=UDP.CDDEPARTMENT 
                                    WHERE
                                        PP.FGACCESSTYPE=2 
                                        AND UDP.CDUSER=831 
                                    UNION
                                    ALL SELECT
                                        PP.FGPERMISSION,
                                        PP.CDPROC,
                                        PP.CDACCESSLIST,
                                        UDP.CDUSER AS USERCD 
                                    FROM
                                        PMPROCACCESSLIST PP 
                                    INNER JOIN
                                        ADUSERDEPTPOS UDP 
                                            ON (
                                                PP.CDDEPARTMENT=UDP.CDDEPARTMENT 
                                                AND PP.CDPOSITION=UDP.CDPOSITION
                                            ) 
                                    WHERE
                                        PP.FGACCESSTYPE=3 
                                        AND UDP.CDUSER=831 
                                    UNION
                                    ALL SELECT
                                        PP.FGPERMISSION,
                                        PP.CDPROC,
                                        PP.CDACCESSLIST,
                                        UDP.CDUSER AS USERCD 
                                    FROM
                                        PMPROCACCESSLIST PP 
                                    INNER JOIN
                                        ADUSERDEPTPOS UDP 
                                            ON PP.CDPOSITION=UDP.CDPOSITION 
                                    WHERE
                                        PP.FGACCESSTYPE=4 
                                        AND UDP.CDUSER=831 
                                    UNION
                                    ALL SELECT
                                        PP.FGPERMISSION,
                                        PP.CDPROC,
                                        PP.CDACCESSLIST,
                                        PP.CDUSER AS USERCD 
                                    FROM
                                        PMPROCACCESSLIST PP 
                                    WHERE
                                        PP.FGACCESSTYPE=5 
                                        AND PP.CDUSER=831 
                                    UNION
                                    ALL SELECT
                                        PP.FGPERMISSION,
                                        PP.CDPROC,
                                        PP.CDACCESSLIST,
                                        US.CDUSER AS USERCD 
                                    FROM
                                        PMPROCACCESSLIST PP CROSS 
                                    JOIN
                                        ADUSER US 
                                    WHERE
                                        PP.FGACCESSTYPE=6 
                                        AND US.CDUSER=831 
                                    UNION
                                    ALL SELECT
                                        PP.FGPERMISSION,
                                        PP.CDPROC,
                                        PP.CDACCESSLIST,
                                        RL.CDUSER AS USERCD 
                                    FROM
                                        PMPROCACCESSLIST PP 
                                    INNER JOIN
                                        ADUSERROLE RL 
                                            ON RL.CDROLE=PP.CDROLE 
                                    WHERE
                                        PP.FGACCESSTYPE=7 
                                        AND RL.CDUSER=831
                                ) PERM1 
                            INNER JOIN
                                PMPROCSECURITYCTRL GNASSOC 
                                    ON (
                                        PERM1.CDACCESSLIST=GNASSOC.CDACCESSLIST 
                                        AND PERM1.CDPROC=GNASSOC.CDPROC
                                    ) 
                            INNER JOIN
                                PMACCESSROLEFIELD GNCTRL 
                                    ON GNASSOC.CDACCESSROLEFIELD=GNCTRL.CDACCESSROLEFIELD 
                            INNER JOIN
                                PMACTIVITY OBJ 
                                    ON GNASSOC.CDPROC=OBJ.CDACTIVITY 
                            INNER JOIN
                                WFPROCESS WFP 
                                    ON WFP.CDPROCESSMODEL=PERM1.CDPROC 
                            WHERE
                                GNCTRL.CDRELATEDFIELD IN (
                                    501
                                ) 
                                AND (
                                    OBJ.FGUSETYPEACCESS=0 
                                    OR OBJ.FGUSETYPEACCESS IS NULL
                                ) 
                                AND WFP.FGMODELWFSECURITY=1 
                                AND WFP.FGSTATUS <= 5 
                            UNION
                            ALL SELECT
                                PERM2.IDOBJECT,
                                PERM2.FGPERMISSION 
                            FROM
                                (SELECT
                                    PP.FGPERMISSION,
                                    WFP.IDOBJECT,
                                    PP.CDPROC,
                                    PP.CDACCESSLIST,
                                    WFP.CDUSERSTART AS USERCD 
                                FROM
                                    PMPROCACCESSLIST PP 
                                INNER JOIN
                                    WFPROCESS WFP 
                                        ON WFP.CDPROCESSMODEL=PP.CDPROC 
                                WHERE
                                    PP.FGACCESSTYPE=30 
                                    AND WFP.CDUSERSTART=831 
                                    AND WFP.FGMODELWFSECURITY=1 
                                    AND WFP.FGSTATUS <= 5 
                                UNION
                                ALL SELECT
                                    PP.FGPERMISSION,
                                    WFP.IDOBJECT,
                                    PP.CDPROC,
                                    PP.CDACCESSLIST,
                                    US.CDLEADER AS USERCD 
                                FROM
                                    PMPROCACCESSLIST PP 
                                INNER JOIN
                                    WFPROCESS WFP 
                                        ON WFP.CDPROCESSMODEL=PP.CDPROC 
                                INNER JOIN
                                    ADUSER US 
                                        ON US.CDUSER=WFP.CDUSERSTART 
                                WHERE
                                    PP.FGACCESSTYPE=31 
                                    AND US.CDLEADER=831 
                                    AND WFP.FGMODELWFSECURITY=1 
                                    AND WFP.FGSTATUS <= 5
                            ) PERM2 
                        INNER JOIN
                            PMPROCSECURITYCTRL GNASSOC 
                                ON (
                                    PERM2.CDACCESSLIST=GNASSOC.CDACCESSLIST 
                                    AND PERM2.CDPROC=GNASSOC.CDPROC
                                ) 
                        INNER JOIN
                            PMACCESSROLEFIELD GNCTRL 
                                ON GNASSOC.CDACCESSROLEFIELD=GNCTRL.CDACCESSROLEFIELD 
                        INNER JOIN
                            PMACTIVITY OBJ 
                                ON GNASSOC.CDPROC=OBJ.CDACTIVITY 
                        WHERE
                            GNCTRL.CDRELATEDFIELD IN (
                                501
                            ) 
                            AND (
                                OBJ.FGUSETYPEACCESS=0 
                                OR OBJ.FGUSETYPEACCESS IS NULL
                            )) PERM99 
                    WHERE
                        1=1 
                    GROUP BY
                        PERM99.IDOBJECT) T 
                    WHERE
                        T.FGPERMISSION=1 
                    UNION
                    ALL SELECT
                        T.IDOBJECT 
                    FROM
                        (SELECT
                            PERM.IDOBJECT,
                            MIN(PERM.FGPERMISSION) AS FGPERMISSION 
                        FROM
                            (SELECT
                                WFP.IDOBJECT,
                                PMA.FGUSETYPEACCESS,
                                PERM1.FGPERMISSION 
                            FROM
                                (SELECT
                                    PM.FGPERMISSION,
                                    PM.CDACTTYPE,
                                    PM.CDACCESSLIST,
                                    TM.CDUSER AS USERCD 
                                FROM
                                    PMACTTYPESECURLIST PM 
                                INNER JOIN
                                    ADTEAMUSER TM 
                                        ON PM.CDTEAM=TM.CDTEAM 
                                WHERE
                                    PM.FGACCESSTYPE=1 
                                    AND TM.CDUSER=831 
                                UNION
                                ALL SELECT
                                    PM.FGPERMISSION,
                                    PM.CDACTTYPE,
                                    PM.CDACCESSLIST,
                                    UDP.CDUSER AS USERCD 
                                FROM
                                    PMACTTYPESECURLIST PM 
                                INNER JOIN
                                    ADUSERDEPTPOS UDP 
                                        ON PM.CDDEPARTMENT=UDP.CDDEPARTMENT 
                                WHERE
                                    PM.FGACCESSTYPE=2 
                                    AND UDP.CDUSER=831 
                                UNION
                                ALL SELECT
                                    PM.FGPERMISSION,
                                    PM.CDACTTYPE,
                                    PM.CDACCESSLIST,
                                    UDP.CDUSER AS USERCD 
                                FROM
                                    PMACTTYPESECURLIST PM 
                                INNER JOIN
                                    ADUSERDEPTPOS UDP 
                                        ON PM.CDDEPARTMENT=UDP.CDDEPARTMENT 
                                        AND PM.CDPOSITION=UDP.CDPOSITION 
                                WHERE
                                    PM.FGACCESSTYPE=3 
                                    AND UDP.CDUSER=831 
                                UNION
                                ALL SELECT
                                    PM.FGPERMISSION,
                                    PM.CDACTTYPE,
                                    PM.CDACCESSLIST,
                                    UDP.CDUSER AS USERCD 
                                FROM
                                    PMACTTYPESECURLIST PM 
                                INNER JOIN
                                    ADUSERDEPTPOS UDP 
                                        ON PM.CDPOSITION=UDP.CDPOSITION 
                                WHERE
                                    PM.FGACCESSTYPE=4 
                                    AND UDP.CDUSER=831 
                                UNION
                                ALL SELECT
                                    PM.FGPERMISSION,
                                    PM.CDACTTYPE,
                                    PM.CDACCESSLIST,
                                    PM.CDUSER AS USERCD 
                                FROM
                                    PMACTTYPESECURLIST PM 
                                WHERE
                                    PM.FGACCESSTYPE=5 
                                    AND PM.CDUSER=831 
                                UNION
                                ALL SELECT
                                    PM.FGPERMISSION,
                                    PM.CDACTTYPE,
                                    PM.CDACCESSLIST,
                                    US.CDUSER AS USERCD 
                                FROM
                                    PMACTTYPESECURLIST PM CROSS 
                                JOIN
                                    ADUSER US 
                                WHERE
                                    PM.FGACCESSTYPE=6 
                                    AND US.CDUSER=831 
                                UNION
                                ALL SELECT
                                    PM.FGPERMISSION,
                                    PM.CDACTTYPE,
                                    PM.CDACCESSLIST,
                                    RL.CDUSER AS USERCD 
                                FROM
                                    PMACTTYPESECURLIST PM 
                                INNER JOIN
                                    ADUSERROLE RL 
                                        ON RL.CDROLE=PM.CDROLE 
                                WHERE
                                    PM.FGACCESSTYPE=7 
                                    AND RL.CDUSER=831
                            ) PERM1 
                        INNER JOIN
                            PMACTTYPESECURCTRL GNASSOC 
                                ON (
                                    PERM1.CDACCESSLIST=GNASSOC.CDACCESSLIST 
                                    AND PERM1.CDACTTYPE=GNASSOC.CDACTTYPE
                                ) 
                        INNER JOIN
                            PMACCESSROLEFIELD GNCTRL 
                                ON GNASSOC.CDACCESSROLEFIELD=GNCTRL.CDACCESSROLEFIELD 
                        INNER JOIN
                            PMACCESSROLEFIELD GNCTRL_F 
                                ON GNCTRL.CDRELATEDFIELD=GNCTRL_F.CDACCESSROLEFIELD 
                        INNER JOIN
                            PMACTIVITY PMA 
                                ON PERM1.CDACTTYPE=PMA.CDACTTYPE 
                        INNER JOIN
                            WFPROCESS WFP 
                                ON PMA.CDACTIVITY=WFP.CDPROCESSMODEL 
                        WHERE
                            GNCTRL_F.CDRELATEDFIELD IN (
                                501
                            ) 
                            AND WFP.FGSTATUS <= 5 
                            AND PMA.FGUSETYPEACCESS=1 
                            AND WFP.FGMODELWFSECURITY=1 
                            AND WFP.CDPRODAUTOMATION IN (
                                160,202
                            ) 
                        UNION
                        ALL SELECT
                            WFP.IDOBJECT,
                            PMA.FGUSETYPEACCESS,
                            PERM2.FGPERMISSION 
                        FROM
                            (SELECT
                                PM.FGPERMISSION,
                                PM.CDACTTYPE,
                                PM.CDACCESSLIST,
                                PMA.CDCREATEDBY AS USERCD 
                            FROM
                                PMACTTYPESECURLIST PM 
                            INNER JOIN
                                PMACTIVITY PMA 
                                    ON PM.CDACTTYPE=PMA.CDACTTYPE 
                            WHERE
                                PM.FGACCESSTYPE=8 
                                AND PMA.CDCREATEDBY=831 
                            UNION
                            ALL SELECT
                                PM.FGPERMISSION,
                                PM.CDACTTYPE,
                                PM.CDACCESSLIST,
                                DEP2.CDUSER 
                            FROM
                                PMACTTYPESECURLIST PM 
                            INNER JOIN
                                PMACTIVITY PMA 
                                    ON PM.CDACTTYPE=PMA.CDACTTYPE 
                            INNER JOIN
                                ADUSERDEPTPOS DEP1 
                                    ON DEP1.CDUSER=PMA.CDCREATEDBY 
                            INNER JOIN
                                ADUSERDEPTPOS DEP2 
                                    ON DEP2.CDDEPARTMENT=DEP1.CDDEPARTMENT 
                            WHERE
                                PM.FGACCESSTYPE=9 
                                AND DEP2.CDUSER=831 
                            UNION
                            ALL SELECT
                                PM.FGPERMISSION,
                                PM.CDACTTYPE,
                                PM.CDACCESSLIST,
                                DEP2.CDUSER 
                            FROM
                                PMACTTYPESECURLIST PM 
                            INNER JOIN
                                PMACTIVITY PMA 
                                    ON PM.CDACTTYPE=PMA.CDACTTYPE 
                            INNER JOIN
                                ADUSERDEPTPOS DEP1 
                                    ON DEP1.CDUSER=PMA.CDCREATEDBY 
                            INNER JOIN
                                ADUSERDEPTPOS DEP2 
                                    ON (
                                        DEP2.CDDEPARTMENT=DEP1.CDDEPARTMENT 
                                        AND DEP2.CDPOSITION=DEP1.CDPOSITION
                                    ) 
                            WHERE
                                PM.FGACCESSTYPE=10 
                                AND DEP2.CDUSER=831 
                            UNION
                            ALL SELECT
                                PM.FGPERMISSION,
                                PM.CDACTTYPE,
                                PM.CDACCESSLIST,
                                DEP2.CDUSER 
                            FROM
                                PMACTTYPESECURLIST PM 
                            INNER JOIN
                                PMACTIVITY PMA 
                                    ON PM.CDACTTYPE=PMA.CDACTTYPE 
                            INNER JOIN
                                ADUSERDEPTPOS DEP1 
                                    ON DEP1.CDUSER=PMA.CDCREATEDBY 
                            INNER JOIN
                                ADUSERDEPTPOS DEP2 
                                    ON DEP2.CDPOSITION=DEP1.CDPOSITION 
                            WHERE
                                PM.FGACCESSTYPE=11 
                                AND DEP2.CDUSER=831 
                            UNION
                            ALL SELECT
                                PM.FGPERMISSION,
                                PM.CDACTTYPE,
                                PM.CDACCESSLIST,
                                US.CDLEADER 
                            FROM
                                PMACTTYPESECURLIST PM 
                            INNER JOIN
                                PMACTIVITY PMA 
                                    ON PM.CDACTTYPE=PMA.CDACTTYPE 
                            INNER JOIN
                                ADUSER US 
                                    ON US.CDUSER=PMA.CDCREATEDBY 
                            WHERE
                                PM.FGACCESSTYPE=12 
                                AND US.CDLEADER=831
                        ) PERM2 
                    INNER JOIN
                        PMACTTYPESECURCTRL GNASSOC 
                            ON (
                                PERM2.CDACCESSLIST=GNASSOC.CDACCESSLIST 
                                AND PERM2.CDACTTYPE=GNASSOC.CDACTTYPE
                            ) 
                    INNER JOIN
                        PMACCESSROLEFIELD GNCTRL 
                            ON GNASSOC.CDACCESSROLEFIELD=GNCTRL.CDACCESSROLEFIELD 
                    INNER JOIN
                        PMACCESSROLEFIELD GNCTRL_F 
                            ON GNCTRL.CDRELATEDFIELD=GNCTRL_F.CDACCESSROLEFIELD 
                    INNER JOIN
                        PMACTIVITY PMA 
                            ON PERM2.CDACTTYPE=PMA.CDACTTYPE 
                    INNER JOIN
                        WFPROCESS WFP 
                            ON PMA.CDACTIVITY=WFP.CDPROCESSMODEL 
                    WHERE
                        GNCTRL_F.CDRELATEDFIELD IN (
                            501
                        ) 
                        AND WFP.FGSTATUS <= 5 
                        AND PMA.FGUSETYPEACCESS=1 
                        AND WFP.FGMODELWFSECURITY=1 
                        AND WFP.CDPRODAUTOMATION IN (
                            160,202
                        ) 
                    UNION
                    ALL SELECT
                        PERM3.IDOBJECT,
                        PMA.FGUSETYPEACCESS,
                        PERM3.FGPERMISSION 
                    FROM
                        (SELECT
                            PM.FGPERMISSION,
                            PM.CDACTTYPE,
                            PM.CDACCESSLIST,
                            WFP.CDUSERSTART AS USERCD,
                            WFP.IDOBJECT 
                        FROM
                            PMACTTYPESECURLIST PM 
                        INNER JOIN
                            PMACTIVITY PMA 
                                ON PM.CDACTTYPE=PMA.CDACTTYPE 
                        INNER JOIN
                            WFPROCESS WFP 
                                ON PMA.CDACTIVITY=WFP.CDPROCESSMODEL 
                        WHERE
                            PM.FGACCESSTYPE=30 
                            AND WFP.CDUSERSTART=831 
                            AND WFP.FGSTATUS <= 5 
                            AND WFP.FGMODELWFSECURITY=1 
                        UNION
                        ALL SELECT
                            PM.FGPERMISSION,
                            PM.CDACTTYPE,
                            PM.CDACCESSLIST,
                            US.CDLEADER AS USERCD,
                            WFP.IDOBJECT 
                        FROM
                            PMACTTYPESECURLIST PM 
                        INNER JOIN
                            PMACTIVITY PMA 
                                ON PM.CDACTTYPE=PMA.CDACTTYPE 
                        INNER JOIN
                            WFPROCESS WFP 
                                ON PMA.CDACTIVITY=WFP.CDPROCESSMODEL 
                        INNER JOIN
                            ADUSER US 
                                ON US.CDUSER=WFP.CDUSERSTART 
                        WHERE
                            PM.FGACCESSTYPE=31 
                            AND US.CDLEADER=831 
                            AND WFP.FGSTATUS <= 5 
                            AND WFP.FGMODELWFSECURITY=1 
                            AND WFP.CDPRODAUTOMATION IN (
                                160,202
                            )
                    ) PERM3 
                INNER JOIN
                    PMACTTYPESECURCTRL GNASSOC 
                        ON (
                            PERM3.CDACCESSLIST=GNASSOC.CDACCESSLIST 
                            AND PERM3.CDACTTYPE=GNASSOC.CDACTTYPE
                        ) 
                INNER JOIN
                    PMACCESSROLEFIELD GNCTRL 
                        ON GNASSOC.CDACCESSROLEFIELD=GNCTRL.CDACCESSROLEFIELD 
                INNER JOIN
                    PMACCESSROLEFIELD GNCTRL_F 
                        ON GNCTRL.CDRELATEDFIELD=GNCTRL_F.CDACCESSROLEFIELD 
                INNER JOIN
                    PMACTIVITY PMA 
                        ON PERM3.CDACTTYPE=PMA.CDACTTYPE 
                WHERE
                    GNCTRL_F.CDRELATEDFIELD IN (
                        501
                    ) 
                    AND PMA.FGUSETYPEACCESS=1) PERM 
            GROUP BY
                PERM.IDOBJECT) T 
            WHERE
                T.FGPERMISSION=1 
            UNION
            ALL SELECT
                AUXWFP.IDOBJECT 
            FROM
                WFPROCESS AUXWFP 
            INNER JOIN
                WFPROCSECURITYLIST WFLIST 
                    ON (
                        AUXWFP.IDOBJECT=WFLIST.IDPROCESS
                    ) 
            INNER JOIN
                WFPROCSECURITYCTRL WFCTRL 
                    ON (
                        WFLIST.CDACCESSLIST=WFCTRL.CDACCESSLIST 
                        AND WFLIST.IDPROCESS=WFCTRL.IDPROCESS
                    ) 
            WHERE
                WFCTRL.CDACCESSROLEFIELD IN (
                    501
                ) 
                AND WFLIST.CDUSER=831 
                AND WFLIST.FGACCESSTYPE=5 
                AND WFLIST.FGACCESSEXCEPTION=1 
                AND WFLIST.FGPERMISSION=1 
                AND AUXWFP.FGSTATUS <= 5
        ) Z
) MYPERM 
    ON (
        WFP.IDOBJECT=MYPERM.IDOBJECT
    ) 
WHERE
WFP.FGSTATUS <= 5 
AND WFP.CDPRODAUTOMATION=202 
AND WFP.FGSTATUS <= 5 
AND INOCCUR.FGOCCURRENCETYPE=2
AND WFS. FGSTATUS IN (2)
AND WFS.FGTYPE in (2,3)) TEMPTB0
) TEMPTB1) TAREAS_PENDIENTES ON TAREAS_PENDIENTES.IDPROCESS = 

TEMP2.ID_HALLAZGO LEFT JOIN
(SELECT 
	
                CASE 
                    WHEN WFS.FGCONCLUDEDSTATUS IS NOT NULL THEN (CASE 
                        WHEN WFS.FGCONCLUDEDSTATUS=1 THEN '#{100900}' 
                        WHEN WFS.FGCONCLUDEDSTATUS=2 THEN '#{100899}' 
                    END) 
                    ELSE (CASE 
                        WHEN WFS.FGTYPE=1 THEN (CASE 
                            WHEN (((SELECT
                                WFPD.DTESTIMATEDFINISH 
                            FROM
                                WFSTRUCT STRUCT 
                            INNER JOIN
                                WFSUBPROCESS SUB 
                                    ON STRUCT.IDOBJECT=SUB.IDOBJECT 
                            INNER JOIN
                                WFPROCESS WFPD 
                                    ON WFPD.IDOBJECT=SUB.IDSUBPROCESS 
                            WHERE
                                STRUCT.IDOBJECT=WFS.IDOBJECT) > (CAST(<!%TODAY%> AS DATE) + COALESCE((SELECT
                                QTDAYS 
                            FROM
                                ADMAILTASKEXEC 
                            WHERE
                                CDMAILTASKEXEC=(SELECT
                                    TASK.CDAHEAD 
                                FROM
                                    ADMAILTASKREL TASK 
                                WHERE
                                    TASK.CDMAILTASKREL=(SELECT
                                        TBL.CDMAILTASKSETTINGS 
                                    FROM
                                        CONOTIFICATION TBL))), 0))) 
                            OR (( SELECT
                                WFPD.DTESTIMATEDFINISH 
                            FROM
                                WFSTRUCT STRUCT 
                            INNER JOIN
                                WFSUBPROCESS SUB 
                                    ON STRUCT.IDOBJECT=SUB.IDOBJECT 
                            INNER JOIN
                                WFPROCESS WFPD 
                                    ON WFPD.IDOBJECT=SUB.IDSUBPROCESS 
                            WHERE
                                STRUCT.IDOBJECT=WFS.IDOBJECT) IS NULL)) THEN '#{100900}' 
                            WHEN (((SELECT
                                WFPD.DTESTIMATEDFINISH 
                            FROM
                                WFSTRUCT STRUCT 
                            INNER JOIN
                                WFSUBPROCESS SUB 
                                    ON STRUCT.IDOBJECT=SUB.IDOBJECT 
                            INNER JOIN
                                WFPROCESS WFPD 
                                    ON WFPD.IDOBJECT=SUB.IDSUBPROCESS 
                            WHERE
                                STRUCT.IDOBJECT=WFS.IDOBJECT)=CAST(<!%TODAY%> AS DATE) 
                            AND (SELECT
                                WFPD.NRTIMEESTFINISH 
                            FROM
                                WFSTRUCT STRUCT 
                            INNER JOIN
                                WFSUBPROCESS SUB 
                                    ON STRUCT.IDOBJECT=SUB.IDOBJECT 
                            INNER JOIN
                                WFPROCESS WFPD 
                                    ON WFPD.IDOBJECT=SUB.IDSUBPROCESS 
                            WHERE
                                STRUCT.IDOBJECT=WFS.IDOBJECT) >= 914) 
                            OR (( SELECT
                                WFPD.DTESTIMATEDFINISH 
                            FROM
                                WFSTRUCT STRUCT 
                            INNER JOIN
                                WFSUBPROCESS SUB 
                                    ON STRUCT.IDOBJECT=SUB.IDOBJECT 
                            INNER JOIN
                                WFPROCESS WFPD 
                                    ON WFPD.IDOBJECT=SUB.IDSUBPROCESS 
                            WHERE
                                STRUCT.IDOBJECT=WFS.IDOBJECT) > CAST(<!%TODAY%> AS DATE))) THEN '#{201639}' 
                            ELSE '#{100899}' 
                        END) 
                        ELSE (CASE 
                            WHEN (( WFS.DTESTIMATEDFINISH > (CAST(<!%TODAY%> AS DATE) + COALESCE((SELECT
                                QTDAYS 
                            FROM
                                ADMAILTASKEXEC 
                            WHERE
                                CDMAILTASKEXEC=(SELECT
                                    TASK.CDAHEAD 
                                FROM
                                    ADMAILTASKREL TASK 
                                WHERE
                                    TASK.CDMAILTASKREL=(SELECT
                                        TBL.CDMAILTASKSETTINGS 
                                    FROM
                                        CONOTIFICATION TBL))), 0))) 
                            OR (WFS.DTESTIMATEDFINISH IS NULL)) THEN '#{100900}' 
                            WHEN (( WFS.DTESTIMATEDFINISH=CAST(<!%TODAY%> AS DATE) 
                            AND WFS.NRTIMEESTFINISH >= 914) 
                            OR (WFS.DTESTIMATEDFINISH > CAST(<!%TODAY%> AS DATE))) THEN '#{201639}' 
                            ELSE '#{100899}' 
                        END) 
                    END) 
                END AS PLAZO,
 				WFP.IDPROCESS IDPROCESS,
 				WFS.IDSTRUCT IDSTRUCT
        from
            WFPROCESS WFP 
        join
            WFSTRUCT WFS 
                ON (
                    WFS.IDPROCESS=WFP.IDOBJECT 
                ) 
		join WFACTIVITY WFA
		ON (WFS.IDOBJECT = WFA.IDOBJECT)

        where
            WFS.fgstatus in (
                2
            ) 
            and WFS.fgtype in (
                2,3
            ) ) ESTADO_TAREAS ON ESTADO_TAREAS.IDPROCESS = TAREAS_PENDIENTES.IDPROCESS AND ESTADO_TAREAS.IDSTRUCT = TAREAS_PENDIENTES.IDSTRUCT